swagger: '2.0'
info:
  title: Calendar API
  version: 1.0.0
host: localhost:3000
schemes:
  - http
tags:
  - name: Calendar
    description: カレンダー関連のAPI
  - name: Event
    description: イベント関連のAPI
paths:
  /calendar/create:
    post:
      tags:
        - Calendar
      summary: カレンダー作成
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - name
              - isPublic
            properties:
              name:
                type: string
              isPublic:
                type: boolean
              users:
                type: array
                items:
                  $ref: '#/definitions/User'
              events:
                type: array
                items:
                  $ref: '#/definitions/EventModel'
      responses:
        '201':
          description: カレンダーが正常に作成されました
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /calendar/{calendarId}:
    get:
      tags:
        - Calendar
      summary: カレンダー取得
      parameters:
        - name: calendarId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: カレンダー情報が正常に取得されました
          schema:
            $ref: '#/definitions/Calendar'
        '404':
          description: カレンダーが見つかりません
        '500':
          description: サーバーエラー

  /calendar/follow:
    put:
      tags:
        - Calendar
      summary: カレンダーフォロー
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - calendarId
            properties:
              calendarId:
                type: string
      responses:
        '200':
          description: カレンダーが正常にフォローされました
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: リクエストが無効です
        '403':
          description: カレンダーは公開されていません
        '500':
          description: サーバーエラー

  /calendar/edit/{calendarId}:
    put:
      tags:
        - Calendar
      summary: カレンダー編集
      parameters:
        - name: calendarId
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              isPublic:
                type: boolean
              ownerUserId:
                type: string
      responses:
        '200':
          description: カレンダーが正常に編集されました
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /calendar/delete/{calendarId}:
    delete:
      tags:
        - Calendar
      summary: カレンダー削除
      parameters:
        - name: calendarId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: カレンダーが正常に削除されました
          schema:
            type: object
            properties:
              message:
                type: string
        '500':
          description: サーバーエラー

  /calendar/unfollow:
    delete:
      tags:
        - Calendar
      summary: 公開カレンダーのフォロー解除
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - calendarId
            properties:
              calendarId:
                type: string
      responses:
        '200':
          description: 公開カレンダーのフォローが正常に解除されました
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: リクエストが無効です
        '404':
          description: 公開カレンダーが見つかりません
        '500':
          description: サーバーエラー

  /calendar/list:
    get:
      tags:
        - Calendar
      summary: ユーザーのカレンダー取得
      responses:
        '200':
          description: ユーザーのカレンダーが正常に取得されました
          schema:
            type: array
            items:
              $ref: '#/definitions/Calendar'
        '500':
          description: サーバーエラー

  /event/create/{calendarId}:
    post:
      tags:
        - Event
      summary: イベント作成
      parameters:
        - name: calendarId
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EventModel'
      responses:
        '201':
          description: イベントが正常に作成されました
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /calendar/public/list:
    get:
      tags:
        - Calendar
      summary: 公開カレンダー取得
      responses:
        '200':
          description: 公開カレンダーが正常に取得されました
          schema:
            type: array
            items:
              $ref: '#/definitions/Calendar'
        '404':
          description: 公開カレンダーが見つかりません
        '500':
          description: サーバーエラー

  /event/list/{calendarId}:
    get:
      tags:
        - Event
      summary: イベント一覧取得
      parameters:
        - name: calendarId
          in: path
          required: true
          type: string
      responses:
        '201':
          description: カレンダーのイベント一覧が正常に取得されました
          schema:
            type: object
            properties:
              message:
                type: string
        '500':
          description: サーバーエラー

  /event/edit/{calendarId}:
    put:
      tags:
        - Event
      summary: イベントの編集
      parameters:
        - name: calendarId
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EventEdit'
      responses:
        '200':
          description: 正常に更新されました
          schema:
            $ref: '#/definitions/EventEdit'
        '400':
          description: リクエストが不正です
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Error unmarshalling request: <error message>"
        '404':
          description: イベントが見つかりません
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Event not found"
        '500':
          description: サーバーエラー
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Error editing event: <error message>"

  /event/delete:
    delete:
      tags:
        - Event
      summary: イベント削除
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - calendarId
              - eventId
            properties:
              calendarId:
                type: string
              eventId:
                type: string
      responses:
        '200':
          description: イベントが正常に削除されました
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /calendar/user/invite:
    post:
      tags:
        - Calendar
      summary: カレンダーにユーザーを招待
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - inviteUserId
              - calendarId
              - accessLevel
            properties:
              inviteUserId:
                type: string
                description: 招待するユーザーのID
              calendarId:
                type: string
                description: カレンダーID
              accessLevel:
                type: string
                enum: [EDITOR, VIEWER]
                description: 付与する権限レベル
      responses:
        '200':
          description: ユーザーが正常に招待されました
          schema:
            type: object
            properties:
              message:
                type: string
                example: "User invited successfully"
        '400':
          description: リクエストが無効です
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid access level. Must be either 'EDITOR' or 'VIEWER'"
        '403':
          description: 権限がありません
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Only the owner can invite users to private calendars"
        '500':
          description: サーバーエラー

definitions:
  Calendar:
    type: object
    properties:
      calendarId:
        type: string
      sortKey:
        type: string
      name:
        type: string
      isPublic:
        type: boolean
      ownerUserId:
        type: string
      users:
        type: array
        items:
          $ref: '#/definitions/User'
      events:
        type: array
        items:
          $ref: '#/definitions/EventModel'
  User:
    type: object
    properties:
      userId:
        type: string
      displayName:
        type: string
      accessLevel:
        type: string
  EventModel:
    type: object
    properties:
      eventId:
        type: string
      title:
        type: string
      description:
        type: string
      startTime:
        type: string
      endTime:
        type: string
      location:
        type: string
      allDay:
        type: boolean
  EventEdit:
    type: object
    required:
      - eventId
    properties:
      eventId:
        type: string
        example: "event1"
      title:
        type: string
        example: "Test Event event1"
      description:
        type: string
        example: "This is test event event1"
      startTime:
        type: string
        format: date-time
        example: "2021-08-01T00:00:00Z"
      endTime:
        type: string
        format: date-time
        example: "2021-08-01T01:00:00Z"
      location:
        type: string
        example: "場所event1"
      allDay:
        type: boolean
        example: false