openapi: 3.0.0
info:
  title: Calendar API
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: Calendar
    description: カレンダー関連のAPI
  - name: Event
    description: イベント関連のAPI
paths:
  /calendar/create/{userId}:
    post:
      tags:
        - Calendar
      summary: カレンダー作成
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - isPublic
              properties:
                name:
                  type: string
                isPublic:
                  type: boolean
                users:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
                events:
                  type: array
                  items:
                    $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: カレンダーが正常に作成されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /calendar/{calendarId}:
    get:
      tags:
        - Calendar
      summary: カレンダー取得
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: カレンダー情報が正常に取得されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'
        '404':
          description: カレンダーが見つかりません
        '500':
          description: サーバーエラー

  /calendar/follow/{calendarId}/{userId}:
    put:
      tags:
        - Calendar
      summary: カレンダーフォロー
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: カレンダーが正常にフォローされました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: カレンダーは公開されていません
        '500':
          description: サーバーエラー

  /calendar/edit/{calendarId}:
    put:
      tags:
        - Calendar
      summary: カレンダー編集
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                isPublic:
                  type: boolean
                ownerUserId:
                  type: string
      responses:
        '200':
          description: カレンダーが正常に編集されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /calendar/delete/{calendarId}:
    delete:
      tags:
        - Calendar
      summary: カレンダー削除
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: カレンダーが正常に削除されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: サーバーエラー

  /calendar/list/{userId}:
    get:
      tags:
        - Calendar
      summary: ユーザーのカレンダー取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ユーザーのカレンダーが正常に取得されました
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Calendar'
        '500':
          description: サーバーエラー

  /event/create/{calendarId}:
    post:
      tags:
        - Event
      summary: イベント作成
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: イベントが正常に作成されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: リクエストが無効です
        '500':
          description: サーバーエラー

  /event/list/{calendarId}:
    get:
      tags:
        - Event
      summary: イベント一覧取得
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: カレンダーのイベント一覧が正常に取得されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: サーバーエラー

components:
  schemas:
    Calendar:
      type: object
      properties:
        calendarId:
          type: string
        sortKey:
          type: string
        name:
          type: string
        isPublic:
          type: boolean
        ownerUserId:
          type: string
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
    User:
      type: object
      properties:
        userId:
          type: string
        displayName:
          type: string
        email:
          type: string
        password:
          type: string
        accessLevel:
          type: string
    Event:
      type: object
      properties:
        eventId:
          type: string
        title:
          type: string
        description:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        location:
          type: string
        allDay:
          type: boolean