AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bonded

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  BondedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main/  # CodeUri を現在のディレクトリに設定
      PackageType: Zip # 画像パッケージではなくZipを使用
      Handler: main    # Handler を main に設定
      Runtime: go1.x
      Timeout: 10 # タイムアウトを10秒に設定
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "http://localhost:8000" # DynamoDBエンドポイントを環境変数として設定
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "Calendars"
      Events:
        CalendarList:
          Type: Api
          Properties:
            Path: /calendar/list
            Method: GET
        CalendarCreate:
          Type: Api
          Properties:
            Path: /calendar/create
            Method: POST

Outputs:
  BondedAPI:
    Description: "API Gateway endpoint URL for Prod environment for Bonded Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}"
  BondedFunction:
    Description: "Bonded Lambda Function ARN"
    Value: !GetAtt BondedFunction.Arn
  BondedFunctionIamRole:
    Description: "Implicit IAM Role created for Bonded function"
    Value: !GetAtt BondedFunctionRole.Arn
