AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bonded

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  BondedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main/        # ソースコードディレクトリ
      PackageType: Zip
      Handler: main         # バイナリ名
      Runtime: go1.x
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "http://host.docker.internal:8000"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "Calendars"
      Events:
        CalendarList:
          Type: Api
          Properties:
            Path: /calendar/list
            Method: GET
        CalendarCreate:
          Type: Api
          Properties:
            Path: /calendar/create
            Method: POST
        CalendarUpdate:                   # 新規追加
          Type: Api
          Properties:
            Path: /calendar/update/{id}
            Method: PUT

Outputs:
  BondedAPI:
    Description: "API Gateway endpoint URL for Prod environment for Bonded Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}"
  BondedFunction:
    Description: "Bonded Lambda Function ARN"
    Value: !GetAtt BondedFunction.Arn
  BondedFunctionIamRole:
    Description: "Implicit IAM Role created for Bonded function"
    Value: !GetAtt BondedFunctionRole.Arn
