AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bonded

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  BondedApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Authorization,X-ID-Token,Content-Type'"
        AllowOrigin: "'http://localhost:5173'"

  BondedFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Environment:
        Variables:
          COGNITO_CLIENT_ID:
          COGNITO_ISSUER:
          COGNITO_JWKS_URL:
          DYNAMODB_ENDPOINT:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "Calendars"
        - DynamoDBCrudPolicy:
            TableName: "Events"
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref BondedApi

    Metadata:
      DockerTag: go-provided.al2-v1
      DockerContext: .
      Dockerfile: Dockerfile
Outputs:
  BondedAPI:
    Description: "API Gateway endpoint URL for Prod environment for Bonded Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}"
  BondedFunction:
    Description: "Bonded Lambda Function ARN"
    Value: !GetAtt BondedFunction.Arn
  BondedFunctionIamRole:
    Description: "Implicit IAM Role created for Bonded function"
    Value: !GetAtt BondedFunctionRole.Arn
