name: Run auto-assign workflow

on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto_assign_config.yml
