name: Run pull-requests workflow

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  auto-assign:
    uses: ./.github/workflows/auto-assign.yml
    secrets: inherit

  golangci-lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
