name: Run pull-requests workflow

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write
  
jobs:
  golangci-lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
